language: python
python:
    - 2.7
    - 3.4
    - 3.6
install:
    - sudo apt-get -y update
    - sudo apt-get -y update
    - sudo apt-get -y install r-base
    - sudo apt-get -y install python-matplotlib
    - pip install codecov
script:
    - nosetests
after_success:
    - codecov

