language: python
python:
    - 3.4
    - 3.6
install:
    - sudo apt-get -y update
    - sudo apt-get -y install python-matplotlib
    - pip install -e .
    - pip install -r test-requirements.txt
script:
    # `py.test` because of python3.4
    - py.test --cov expressivar --cov-report=term --cov-report=xml
#after_success:
#    - codecov -t 'foo'

